#!/bin/sh

# bbman 1.1 - 2012 June 15
# Displays man pages in BBEdit

# This script is provided under The MIT License (MIT)
# Copyright (c) 2012 height8, www.height8.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, 
# including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished 
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
# THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


[ $# -eq 0 ] && {
	echo "Usage: bbman [section] name"
	echo "Display a man page (optionally from a specific section) in BBEdit"
	exit 1
}

[ $# -eq 2 ] && {
	man $1 $2 | col -b | bbedit --clean --view-top -t "man $1 $2"
	exit 0
}
man $1 | col -b | bbedit --clean --view-top -t "man $1"
