#!/bin/sh

# bbschema 1.1 - 2012 July 23
# Takes one or more parameters as database names, performs mysqldump compact on them, and sends the output to bbschemaparse
# Acts as front-end to bbschemaparse

# This script is provided under The MIT License (MIT)
# Copyright (c) 2012 height8, www.height8.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, 
# including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished 
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
# THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

[ $# -eq 0 ] && {
	echo "Error, please supply one or more database names"
	echo "Usage: bbschema databasename [databasename] [databasename] ..."
	exit 1
}

# Thank you http://stackoverflow.com/a/4785518 for this method:
command -v bbschemaparse >/dev/null 2>&1 || { echo "Can't find bbschemaparse in the PATH, can't continue." >&2; exit 1; }
command -v mysqldump >/dev/null 2>&1 || { echo "Can't find mysqldump in the PATH, can't continue." >&2; exit 1; }

mysqldump -u root -p -h 127.0.0.1 --no-data --compact --databases $@  | bbschemaparse
